#include "Editor/ScriptProject.h"

#include <Engine/Core/Log.h>
#include <Engine/Core/Platform.h>
#include <Engine/Scripting/ScriptEngine.h>

#include <chrono>
#include <format>
#include <fstream>
#include <iterator>
#include <set>
#include <sstream>
#include <string>
#include <utility>

namespace ByteForge
{
    namespace
    {
        constexpr const char* TargetFramework = "net10.0";

        std::string Quote(const std::filesystem::path& path)
        {
            return std::format("\"{}\"", path.string());
        }

        std::string ReadFile(const std::filesystem::path& path)
        {
            std::ifstream file(path, std::ios::binary);
            return { std::istreambuf_iterator<char>(file), std::istreambuf_iterator<char>() };
        }

        void ReportBuildOutput(const std::string& output)
        {
            std::set<std::string> reported;
            bool anyError = false;

            std::istringstream lines(output);
            for (std::string line; std::getline(lines, line);)
            {
                const bool error = line.contains(": error ");
                const bool warning = line.contains(": warning ");
                if ((!error && !warning) || !reported.insert(line).second) continue;

                if (error)
                {
                    APP_ERROR("{}", line);
                    anyError = true;
                } else
                    APP_WARN("{}", line);
            }

            if (!anyError)
                APP_ERROR("C# build failed:\n{}", output);
        }
    }

    ScriptProject::ScriptProject(std::filesystem::path root)
        : m_Root(std::move(root)) {}

    void ScriptProject::GenerateProjectFile() const
    {
        const std::filesystem::path scriptCore = Platform::GetExecutableDirectory() / "ScriptCore" / "ScriptCore.dll";

        const std::string content = std::format(R"(
<Project Sdk="Microsoft.NET.Sdk">
<!-- Generated by the ByteForge editor on startup; edits are overwritten -->

  <PropertyGroup>
    <TargetFramework>{}</TargetFramework>
    <AssemblyName>GameScripts</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- Only scripts from the asset folder: no engine sources, no build output -->
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="assets/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ScriptCore">
      <HintPath>{}</HintPath>
      <!-- Provided by the engine at runtime, never copied next to the game assembly -->
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
)", TargetFramework, scriptCore.string());

        const std::filesystem::path file = GetProjectFile();
        if (ReadFile(file) == content) return;

        std::ofstream(file, std::ios::binary | std::ios::trunc) << content;
        APP_INFO("Generated {}", file.filename().string());
    }

    bool ScriptProject::Reload() const
    {
        ScriptBackend* backend = ScriptEngine::Get().FindBackendByName("C#");
        if (backend == nullptr)
        {
            APP_WARN("C# scripting is unavailable, game scripts are not built");
            return false;
        }

        GenerateProjectFile();

        const auto start = std::chrono::steady_clock::now();
        const Platform::ProcessResult result = Platform::RunProcess(std::format(
            "dotnet build {} -c Debug -o {} --nologo -v quiet", Quote(GetProjectFile()), Quote(GetOutputDirectory())));

        if (result.ExitCode != 0)
        {
            ReportBuildOutput(result.Output);
            return false;
        }

        const auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(
            std::chrono::steady_clock::now() - start);
        APP_INFO("C# scripts built in {} ms", elapsed.count());

        return backend->LoadModule(GetOutputDirectory() / "GameScripts.dll");
    }
}
