#include "Editor/ScriptProject.h"

#include <Engine/Core/Log.h>
#include <Engine/Core/Platform.h>
#include <Engine/Core/JobSystem.h>
#include <Engine/Assets/AssetRegistry.h>
#include <Engine/Scripting/ScriptEngine.h>

#include <chrono>
#include <format>
#include <fstream>
#include <iterator>
#include <set>
#include <sstream>
#include <string>
#include <utility>
#include <vector>
#include <exception>
#include <future>

namespace ByteForge
{
    namespace
    {
        constexpr const char* TargetFramework = "net10.0";

        std::string Quote(const std::filesystem::path& path)
        {
            return std::format("\"{}\"", path.string());
        }

        std::string ReadFile(const std::filesystem::path& path)
        {
            std::ifstream file(path, std::ios::binary);
            return { std::istreambuf_iterator<char>(file), std::istreambuf_iterator<char>() };
        }

        void ReportBuildOutput(const std::string& output)
        {
            std::set<std::string> reported;
            bool anyError = false;

            std::istringstream lines(output);
            for (std::string line; std::getline(lines, line);)
            {
                const bool error = line.contains(": error ");
                const bool warning = line.contains(": warning ");
                if ((!error && !warning) || !reported.insert(line).second) continue;

                if (error)
                {
                    APP_ERROR("{}", line);
                    anyError = true;
                } else
                    APP_WARN("{}", line);
            }

            if (!anyError)
                APP_ERROR("C# build failed:\n{}", output);
        }
    }

    ScriptProject::ScriptProject(std::filesystem::path root)
        : m_Root(std::move(root)) {}

    void ScriptProject::GenerateProjectFile() const
    {
        const std::filesystem::path scriptCore = Platform::GetExecutableDirectory() / "ScriptCore" / "ScriptCore.dll";

        const std::string content = std::format(R"(
<Project Sdk="Microsoft.NET.Sdk">
<!-- Generated by the ByteForge editor on startup; edits are overwritten -->

  <PropertyGroup>
    <TargetFramework>{}</TargetFramework>
    <AssemblyName>GameScripts</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- Only scripts from the asset folder: no engine sources, no build output -->
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="assets/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ScriptCore">
      <HintPath>{}</HintPath>
      <!-- Provided by the engine at runtime, never copied next to the game assembly -->
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
)", TargetFramework, scriptCore.string());

        const std::filesystem::path file = GetProjectFile();
        if (ReadFile(file) == content) return;

        std::ofstream(file, std::ios::binary | std::ios::trunc) << content;
        APP_INFO("Generated {}", file.filename().string());
    }

    void ScriptProject::RequestReload()
    {
        if (IsBuilding())
        {
            m_ReloadQueued = true;
            return;
        }

        StartBuild();
    }

    void ScriptProject::Update(const bool canLoad)
    {
        if (!IsBuilding() || !canLoad) return;
        if (m_Build.wait_for(std::chrono::seconds(0)) != std::future_status::ready) return;

        FinishBuild();

        if (m_ReloadQueued)
        {
            m_ReloadQueued = false;
            StartBuild();
        }
    }

    float ScriptProject::GetBuildSeconds() const
    {
        if (!IsBuilding())
            return 0.0f;

        return std::chrono::duration<float>(std::chrono::steady_clock::now() - m_BuildStart).count();
    }

    void ScriptProject::StartBuild()
    {
        if (ScriptEngine::Get().FindBackendByName("C#") == nullptr)
        {
            APP_WARN("C# scripting is unavailable, game scripts are not built");
            return;
        }

        GenerateProjectFile();

        std::string command = std::format("dotnet build {} -c Debug -o {} --nologo -v quiet",
                                          Quote(GetProjectFile()), Quote(GetOutputDirectory()));

        m_BuildStart = std::chrono::steady_clock::now();

        m_Build = JobSystem::Submit([command = std::move(command)] { return Platform::RunProcess(command); });
    }

    void ScriptProject::FinishBuild()
    {
        const auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(
            std::chrono::steady_clock::now() - m_BuildStart);

        Platform::ProcessResult result;
        try
        {
            result = m_Build.get();
        } catch (const std::exception& e)
        {
            APP_ERROR("C# build could not run: {}", e.what());
            return;
        }

        if (result.ExitCode != 0)
        {
            ReportBuildOutput(result.Output);
            return;
        }

        APP_INFO("C# scripts built in {} ms", elapsed.count());

        if (ScriptBackend* backend = ScriptEngine::Get().FindBackendByName("C#"))
            backend->LoadModule(GetOutputDirectory() / "GameScripts.dll");
    }

    std::expected<std::string, std::string> ScriptProject::FindClassForAsset(const UUID scriptAsset)
    {
        AssetMetadata metadata;
        if (!AssetRegistry::TryGetMetadata(scriptAsset, metadata) || metadata.Type != AssetType::Script)
            return std::unexpected("Not a script asset");

        const std::string fileName = metadata.Path.filename().string();
        const std::string expected = metadata.Path.stem().string();

        std::vector<std::string> matches;
        for (const ScriptClassInfo& info : ScriptEngine::Get().GetClasses())
        {
            if (info.Backend != "C#") continue;

            const std::string_view name = info.Name;
            if (name.substr(name.find_last_of('.') + 1) == expected)
                matches.push_back(info.Name);
        }

        if (matches.empty())
            return std::unexpected(std::format("No script class named '{}' in {} (class and file name must match, "
                                               "or the scripts need a reload)", expected, fileName));

        if (matches.size() > 1)
        {
            std::string list;
            for (const std::string& match : matches)
                list += (list.empty() ? "" : ", ") + match;
            return std::unexpected(std::format("'{}' is ambiguous: {}", expected, list));
        }

        return std::move(matches.front());
    }
}
